# Generated by Django 5.1.4 on 2025-04-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculteurs',
            name='photo_profil',
            field=models.FileField(upload_to='photo_profile/'),
        ),
    ]
