# Generated by Django 5.1.4 on 2025-05-09 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_messages_forum_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_forum',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='messages_audio/'),
        ),
        migrations.AddField(
            model_name='messages_privees',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='messages_audio/'),
        ),
        migrations.AddField(
            model_name='sujets_forum',
            name='participants',
            field=models.ManyToManyField(related_name='forum_sujets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages_forum',
            name='sujet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.sujets_forum'),
        ),
    ]
