# Generated by Django 5.1.4 on 2025-04-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_agriculteurs_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='image_url',
        ),
        migrations.AddField(
            model_name='publications',
            name='image',
            field=models.FileField(default=None, upload_to='publication-images/'),
            preserve_default=False,
        ),
    ]
